function [fitResult] = multiGaussFit(x, y, firstPeak, peakWidthGuess)

% multiGaussFit fits the sum of several gaussians to the data x and y.
%
% firstPeak is the position of the first peak for fitting.
% peakWidthGuess is a guess at the gaussian width so the fit know where to
% start.
% The function fits the gaussians simultaneously, i.e. the sum of (eight)
% gaussians.
% Note that this function needs some work to make it more general.


% Number of peaks to fit (defined by the fit function below).
% In this version of the function, you will need to change the fit function
% if you want to change numberofpeaks.
numberofpeaks = 8;

% Generate starting value for centre positions of gaussians.
for ii=1:numberofpeaks
    slice_centre(ii) = firstPeak + 120*(ii-1);
end

% Flip data from row to column vector for fitting.
slice_centre = slice_centre';

         
%% Fit options         
fo = fitoptions('Method','NonlinearLeastSquares',...
               'Lower',[0,slice_centre(1)-peakWidthGuess(1),10, ...
                        10,slice_centre(2)-peakWidthGuess(1),10, ...
                        10,slice_centre(3)-peakWidthGuess(1),10, ... 
                        10,slice_centre(4)-peakWidthGuess(1),10, ...
                        10,slice_centre(5)-peakWidthGuess(1),10, ...
                        10,slice_centre(6)-peakWidthGuess(1),10, ...
                        10,slice_centre(7)-peakWidthGuess(1),10, ...
                        10,slice_centre(8)-peakWidthGuess(1),10, ...
                        -10], ...
               'Upper',[100,slice_centre(1)+peakWidthGuess(1),100, ...
                        100,slice_centre(2)+peakWidthGuess(1),60, ...
                        100,slice_centre(3)+peakWidthGuess(1),60, ... 
                        100,slice_centre(4)+peakWidthGuess(1),60, ...
                        100,slice_centre(5)+peakWidthGuess(1),60, ...
                        100,slice_centre(6)+peakWidthGuess(1),60, ...
                        100,slice_centre(7)+peakWidthGuess(1),60, ...
                        100,slice_centre(8)+peakWidthGuess(1),60, ...
                        +10], ...
               'StartPoint',[60,slice_centre(1),20, ...
                        60,slice_centre(2),20, ...
                        60,slice_centre(3),20, ... 
                        60,slice_centre(4),20, ...
                        60,slice_centre(5),20, ...
                        60,slice_centre(6),20, ...
                        60,slice_centre(7),20, ...
                        60,slice_centre(8),20, ...
                        0]);

%% Fit function, relating the fit options above.
% The number of gaussians corresponds to the numberofpeaks specified above.
ft = fittype(['a*exp(-(x-aa).^2/(2*aaa^2)) + b*exp(-(x-bb).^2/(2*bbb^2))' ...
             '+ c*exp(-(x-cc).^2/(2*ccc^2)) + d*exp(-(x-dd).^2/(2*ddd^2))' ...
             '+ e*exp(-(x-ee).^2/(2*eee^2)) + f*exp(-(x-ff).^2/(2*fff^2))' ...
             '+ g*exp(-(x-gg).^2/(2*ggg^2)) + h*exp(-(x-hh).^2/(2*hhh^2))+p'],'options',fo);

% Make fit
[fitResult] = fit(x,y,ft); % return fit result.

% end of file.